apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroloom-web
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroloom-core
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroloom-account-edge
spec:
  replicas: 2
