set client_encoding = 'UTF8';

insert into users (id, username, email, created_at, updated_at, last_login_at)
values
  ('demo-user-front', '前端观察员', null, now(), now(), now()),
  ('demo-user-ops', '终端巡检员', null, now(), now(), now()),
  ('demo-user-data', '渠道勘验员', null, now(), now(), now())
on conflict (id) do update
set username = excluded.username,
    updated_at = now();

delete from opinion_topic_comments
where topic_id like 'demo-opinion-%';

delete from opinion_topic_supports
where topic_id like 'demo-opinion-%';

delete from opinion_topic_opposes
where topic_id like 'demo-opinion-%';

delete from opinion_topics
where id like 'demo-opinion-%';

insert into opinion_topics (
  id,
  creator_user_id,
  title,
  summary,
  description,
  requirements,
  tags,
  difficulty_level,
  creation_ticket_cost,
  target_support_count,
  support_ticket_total,
  oppose_ticket_total,
  unique_supporter_count,
  unique_opposer_count,
  support_rate_threshold,
  status,
  review_status,
  discussion_status,
  moderation_reason_category,
  moderation_reason_detail,
  moderation_note,
  reviewed_at,
  reviewed_by_user_id,
  comment_count,
  last_commented_at,
  adopted_at,
  adopted_by_user_id,
  archived_at,
  banned_at,
  deleted_at,
  created_at,
  updated_at
)
values
  (
    'demo-opinion-ui-density',
    'demo-user-front',
    '优化议题面板的榜单密度',
    '把左侧榜单的筛选与信息层级再压缩一档，减少空白并提升可读性。',
    '当前议题界面的目录 rail 已经有基本结构，但榜单头部与列表之间的留白仍然偏大，切换条件过多时会压缩真正的榜单可视面积。建议继续收紧顶部控件，并让常用筛选保持一层可达，低频筛选折叠到下拉里。',
    null,
    array['uiOptimization','flowOptimization']::text[],
    3,
    10,
    100,
    26,
    2,
    4,
    1,
    0.6000,
    'collecting',
    'published',
    'open',
    null,
    null,
    null,
    now() - interval '4 days',
    'demo-user-front',
    3,
    now() - interval '2 days',
    null,
    null,
    null,
    null,
    null,
    now() - interval '5 days',
    now() - interval '2 days'
  ),
  (
    'demo-opinion-channel-mirror',
    'demo-user-data',
    '增加海外镜像下载渠道',
    '为常用资源补充海外镜像与地区说明，降低下载失败率。',
    '不少用户在不同网络区域访问资源时会遇到超时或速度不稳定的问题。建议在资源页增加海外镜像渠道说明，并在可行时做地区分流提示，减少下载摩擦。',
    null,
    array['channelExpansion','newFeature']::text[],
    3,
    10,
    100,
    18,
    1,
    3,
    1,
    0.6000,
    'collecting',
    'published',
    'open',
    null,
    null,
    null,
    now() - interval '3 days',
    'demo-user-data',
    2,
    now() - interval '32 hours',
    null,
    null,
    null,
    null,
    null,
    now() - interval '4 days',
    now() - interval '32 hours'
  ),
  (
    'demo-opinion-notify-subscribe',
    'local-dev-account',
    '新增议题变更通知订阅',
    '允许用户订阅自己关注议题的状态变化与新回复提醒。',
    '当前议题页适合持续讨论，但用户离开页面后很难知道某个议题是否有新回复、是否被采纳或是否进入候补。建议增加轻量的订阅机制，将状态变化推送到站内邮箱或通知中心。',
    null,
    array['newFeature','flowOptimization']::text[],
    3,
    10,
    100,
    14,
    0,
    3,
    0,
    0.6000,
    'qualified',
    'published',
    'open',
    null,
    null,
    null,
    now() - interval '2 days',
    'local-dev-account',
    1,
    now() - interval '28 hours',
    null,
    null,
    null,
    null,
    null,
    now() - interval '3 days',
    now() - interval '28 hours'
  ),
  (
    'demo-opinion-mailbox-performance',
    'demo-user-ops',
    '优化邮箱中心首屏性能',
    '减少邮箱中心首屏加载时的聚合请求与卡顿。',
    '邮箱中心已经承担很多聚合能力，如果首屏需要拉取过多附带信息，会影响玩家第一时间看到核心内容。建议审视邮箱首屏的数据拆分，将低优先级块延后加载。',
    null,
    array['performance','uiOptimization']::text[],
    3,
    10,
    100,
    11,
    4,
    2,
    2,
    0.6000,
    'collecting',
    'published',
    'open',
    null,
    null,
    null,
    now() - interval '2 days',
    'demo-user-ops',
    2,
    now() - interval '20 hours',
    null,
    null,
    null,
    null,
    null,
    now() - interval '2 days',
    now() - interval '20 hours'
  ),
  (
    'demo-opinion-tag-guideline',
    'demo-user-front',
    '建立提案标签使用指引',
    '为提案标签提供明确的使用说明，减少分类混乱。',
    '标签筛选已经进入议题中心，但如果没有清晰规则，用户容易在“新功能”“其他”“流程优化”之间随意选择，导致筛选失真。建议在创建议题时提供简短的标签定义说明。',
    null,
    array['other','flowOptimization']::text[],
    3,
    10,
    100,
    9,
    1,
    2,
    1,
    0.6000,
    'collecting',
    'published',
    'open',
    null,
    null,
    null,
    now() - interval '36 hours',
    'demo-user-front',
    1,
    now() - interval '18 hours',
    null,
    null,
    null,
    null,
    null,
    now() - interval '40 hours',
    now() - interval '18 hours'
  ),
  (
    'demo-opinion-creator-channel',
    'demo-user-data',
    '增加创作者合作渠道入口',
    '在账户终端补充创作者合作与入驻渠道入口。',
    '部分创作者想提交合作申请或了解渠道政策，但当前入口比较分散。建议增加统一入口，将合作说明、资格要求与提交流程集中收口。',
    null,
    array['channelExpansion','other']::text[],
    3,
    10,
    100,
    7,
    0,
    2,
    0,
    0.6000,
    'collecting',
    'published',
    'open',
    null,
    null,
    null,
    now() - interval '30 hours',
    'demo-user-data',
    0,
    null,
    null,
    null,
    null,
    null,
    null,
    now() - interval '34 hours',
    now() - interval '30 hours'
  );

insert into opinion_topic_supports (id, topic_id, user_id, ticket_amount, created_at)
values
  ('demo-support-1', 'demo-opinion-ui-density', '02a2ad31-80a0-458d-a9d4-68cca97d6275', 8, now() - interval '4 days'),
  ('demo-support-2', 'demo-opinion-ui-density', 'local-dev-account', 6, now() - interval '3 days'),
  ('demo-support-3', 'demo-opinion-ui-density', 'local-dev-2', 7, now() - interval '3 days'),
  ('demo-support-4', 'demo-opinion-ui-density', 'demo-user-ops', 5, now() - interval '2 days'),
  ('demo-support-5', 'demo-opinion-channel-mirror', '02a2ad31-80a0-458d-a9d4-68cca97d6275', 4, now() - interval '3 days'),
  ('demo-support-6', 'demo-opinion-channel-mirror', 'local-dev-2', 7, now() - interval '2 days'),
  ('demo-support-7', 'demo-opinion-channel-mirror', 'demo-user-data', 7, now() - interval '32 hours'),
  ('demo-support-8', 'demo-opinion-notify-subscribe', '02a2ad31-80a0-458d-a9d4-68cca97d6275', 3, now() - interval '2 days'),
  ('demo-support-9', 'demo-opinion-notify-subscribe', 'local-dev-account', 5, now() - interval '40 hours'),
  ('demo-support-10', 'demo-opinion-notify-subscribe', 'demo-user-ops', 6, now() - interval '28 hours'),
  ('demo-support-11', 'demo-opinion-mailbox-performance', 'local-dev-2', 6, now() - interval '26 hours'),
  ('demo-support-12', 'demo-opinion-mailbox-performance', 'demo-user-front', 5, now() - interval '20 hours'),
  ('demo-support-13', 'demo-opinion-tag-guideline', '02a2ad31-80a0-458d-a9d4-68cca97d6275', 5, now() - interval '22 hours'),
  ('demo-support-14', 'demo-opinion-tag-guideline', 'demo-user-ops', 4, now() - interval '18 hours'),
  ('demo-support-15', 'demo-opinion-creator-channel', 'local-dev-account', 3, now() - interval '31 hours'),
  ('demo-support-16', 'demo-opinion-creator-channel', 'demo-user-data', 4, now() - interval '30 hours');

insert into opinion_topic_opposes (id, topic_id, user_id, ticket_amount, created_at)
values
  ('demo-oppose-1', 'demo-opinion-ui-density', 'demo-user-data', 2, now() - interval '42 hours'),
  ('demo-oppose-2', 'demo-opinion-channel-mirror', 'local-dev-account', 1, now() - interval '30 hours'),
  ('demo-oppose-3', 'demo-opinion-mailbox-performance', '02a2ad31-80a0-458d-a9d4-68cca97d6275', 2, now() - interval '24 hours'),
  ('demo-oppose-4', 'demo-opinion-mailbox-performance', 'demo-user-data', 2, now() - interval '20 hours'),
  ('demo-oppose-5', 'demo-opinion-tag-guideline', 'local-dev-account', 1, now() - interval '18 hours');

insert into opinion_topic_comments (
  id,
  topic_id,
  author_user_id,
  parent_comment_id,
  reply_to_comment_id,
  reply_to_user_id,
  content,
  ticket_cost,
  created_at,
  updated_at
)
values
  (
    'demo-comment-1',
    'demo-opinion-ui-density',
    'demo-user-front',
    null,
    null,
    null,
    '建议把当前榜单头部再收紧一档，顶部只保留高频筛选，把低频项折叠到更轻的入口里。',
    1,
    now() - interval '3 days',
    now() - interval '3 days'
  ),
  (
    'demo-comment-2',
    'demo-opinion-ui-density',
    '02a2ad31-80a0-458d-a9d4-68cca97d6275',
    'demo-comment-1',
    'demo-comment-1',
    'demo-user-front',
    '同意，尤其标签筛选不要单独占一整排，应该尽量并到榜单控制区里。',
    1,
    now() - interval '52 hours',
    now() - interval '52 hours'
  ),
  (
    'demo-comment-3',
    'demo-opinion-ui-density',
    'local-dev-account',
    null,
    null,
    null,
    '如果还要保留额外信息，建议下沉到右侧详情板，不要继续塞进左侧 rail。',
    1,
    now() - interval '2 days',
    now() - interval '2 days'
  ),
  (
    'demo-comment-4',
    'demo-opinion-channel-mirror',
    'demo-user-ops',
    null,
    null,
    null,
    '渠道增加以后，最好顺手补充对应地区的下载说明和失败后的备用入口。',
    1,
    now() - interval '36 hours',
    now() - interval '36 hours'
  ),
  (
    'demo-comment-5',
    'demo-opinion-channel-mirror',
    'demo-user-data',
    'demo-comment-4',
    'demo-comment-4',
    'demo-user-ops',
    '可以，后续也可以把地区说明挂到资源详情页，避免用户来回切换。',
    1,
    now() - interval '32 hours',
    now() - interval '32 hours'
  ),
  (
    'demo-comment-6',
    'demo-opinion-notify-subscribe',
    'local-dev-account',
    null,
    null,
    null,
    '如果做订阅，优先接站内邮箱和公告红点就够了，先不要引入新的外部通知通道。',
    1,
    now() - interval '28 hours',
    now() - interval '28 hours'
  );
