import assert from "node:assert/strict";
import { describe, it } from "node:test";

import type { GatewayAnalysisAnomalyIncidentAlertQueueItemView } from "@neuro/contracts";

import { buildGatewayAnomalyIncidentAlertPayload } from "./gateway-anomaly-alert-payload";

describe("gateway anomaly alert dispatch helpers", () => {
  it("builds a stable payload from the alert queue item", () => {
    const payload = buildGatewayAnomalyIncidentAlertPayload({
      incident: {
        id: "incident_123",
        policyId: "policy-gateway-critical",
        fingerprint: "fp_gateway",
        projectId: "project_alpha",
        routePolicyId: "route_project_alpha",
        tag: "rolling",
        textMode: "preview_redacted",
        code: "failure_rate_spike",
        severity: "critical",
        status: "open",
        ownerUserId: "user_gateway_owner",
        followUpStatus: "investigating",
        syncHitCount: 4,
        escalationStatus: "escalated",
        escalatedAt: "2026-04-06T09:00:00.000Z",
        escalationReason: "Auto escalated after repeated failure spikes.",
        latestNote: null,
        resolutionNote: null,
        lastActionAt: null,
        lastAlertAttemptAt: null,
        lastAlertedAt: null,
        lastAlertSeverity: null,
        alertDeliveryCount: 0,
        summary: "failure spikes persisted after the latest route rollout",
        latestExportId: "export_new",
        previousExportId: "export_old",
        latestValue: 0.31,
        previousValue: 0.1,
        deltaValue: 0.21,
        deltaRatio: 2.1,
        thresholdValue: 0.15,
        firstSeenAt: "2026-04-06T08:00:00.000Z",
        lastSeenAt: "2026-04-06T09:00:00.000Z",
        acknowledgedAt: null,
        resolvedAt: null,
        createdAt: "2026-04-06T08:00:00.000Z",
        updatedAt: "2026-04-06T09:00:00.000Z",
      },
      policy: {
        id: "policy-gateway-critical",
        name: "Gateway Critical Guard",
        status: "enabled",
        projectId: "project_alpha",
        routePolicyId: "route_project_alpha",
        tag: "rolling",
        textMode: "preview_redacted",
        profileKey: "balanced",
        thresholds: {
          failureRateWarningThreshold: 0.15,
          failureRateCriticalThreshold: 0.25,
          failureRateDeltaRatioThreshold: 0.5,
          completionRateWarningThreshold: 0.75,
          completionRateCriticalThreshold: 0.6,
          completionRateDeltaValueThreshold: -0.1,
          responseArtifactCoverageWarningThreshold: 0.8,
          responseArtifactCoverageCriticalThreshold: 0.6,
          responseArtifactCoverageDeltaValueThreshold: -0.1,
          requestArtifactCoverageWarningThreshold: 0.85,
          requestArtifactCoverageCriticalThreshold: 0.65,
          requestArtifactCoverageDeltaValueThreshold: -0.1,
          tokensPerSampleWarningDeltaRatioThreshold: 0.35,
          tokensPerSampleCriticalDeltaRatioThreshold: 0.8,
          tokensPerSampleCriticalAbsoluteThreshold: 2000,
        },
        autoSyncEnabled: true,
        autoSyncIntervalMinutes: 60,
        lastSyncedAt: null,
        lastSyncStatus: null,
        lastSyncError: null,
        nextSyncDueAt: null,
        syncDue: true,
        autoEscalateEnabled: true,
        escalateSeverityThreshold: "critical",
        escalateAfterSyncCount: 3,
        autoEscalateOwnerUserId: "ops_1",
        autoEscalateFollowUpStatus: "investigating",
        autoRemediationEnabled: true,
        autoRemediationIntervalMinutes: 180,
        autoRemediationDryRunFirst: true,
        autoRemediationActionKeys: ["disable-prestream-fallback"],
        autoRemediationMaxApplyRunsPerIncident: 1,
        autoRemediationRequireAlertBeforeApply: false,
        autoRemediationFreezeOnProviderHealthDegrade: true,
        alertingEnabled: true,
        alertIntervalMinutes: 180,
        notifyOperatorsOnEscalation: true,
        notifyOwnerOnEscalation: true,
        createdAt: "2026-04-06T08:00:00.000Z",
        updatedAt: "2026-04-06T08:00:00.000Z",
      },
      routePolicy: { id: "route_project_alpha", projectId: "project_alpha", name: "default", isDefault: true, enabled: true, config: {
        stickySessions: true,
        preStreamFallbackEnabled: true,
        selectionStrategy: "priority",
        providerLoadAwareRoutingEnabled: true,
        maxConcurrentRequests: 10,
        providerMaxConcurrentRequests: 3,
        rateLimitWindowSeconds: null,
        rateLimitMaxRequests: null,
        apiKeyRateLimit: null,
        modelRateLimits: null,
        endpointRateLimits: null,
        circuitBreakerThreshold: 3,
        circuitBreakerCooldownSeconds: 60,
        allowedProviderAccountIds: ["provider_1"],
        allowedProtocolFamilies: ["openai"],
        allowedModelIds: null,
        blockedModelIds: null,
        maxRequestBodyBytes: null,
        streamIdleTimeoutSeconds: null,
        totalRequestTimeoutSeconds: null,
        maxStreamHeartbeatGapSeconds: null,
        routingAnomalyAutoRemediation: null,
        rateLimitHotspotAutoRemediation: null,
        fallbackHttpStatuses: [429, 500],
        fallbackErrorCodes: ["upstream_error"],
      }, createdAt: "2026-04-06T08:00:00.000Z", updatedAt: "2026-04-06T08:00:00.000Z" },
      alertIntervalMinutes: 180,
      alertDue: true,
      nextAlertDueAt: null,
      notifyOperators: true,
      notifyOwner: true,
      alertLevel: 3,
      webhookSeverity: "danger",
      remediationActionKeys: ["routing-review", "provider-isolation"],
    } satisfies GatewayAnalysisAnomalyIncidentAlertQueueItemView);

    assert.equal(payload.alertLevel, 3);
    assert.equal(payload.severity, "danger");
    assert.equal(payload.reasonCategory, "failure_rate_spike");
    assert.equal(payload.followUpStatus, "investigating");
    assert.equal(payload.policyId, "policy-gateway-critical");
    assert.equal(payload.projectId, "project_alpha");
    assert.equal(payload.incidentId, "incident_123");
    assert.equal(payload.routePolicyId, "route_project_alpha");
    assert.equal(payload.candidateCount, 2);
  });
});
